services:
  - type: web
    name: kltochique-realtime-v4
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_TOKEN
        sync: false
      - key: AGENT_KEY
        sync: false
